name: release-solution-to-qa
# prepare for releasing to qa:
#   convert solution to managed (using a build PowerPlatform environment for the conversion) - we will not use a managed solution in this context
#   upload the solution to the GitHub artifacts and deploy to the QA environment

on:
  push:
    branches: [ main ]
    paths:
      - 'TeamsCreationAutomationWithPowerAutomate/**'

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: TeamsCreationAutomationWithPowerAutomate/TeamsCreation
        solution-file: out/TeamsCreationAutomationWithPowerAutomate/TeamsCreation.zip
        solution-type: Unmanaged

    # 2 next actions not useful in our context
    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ secrets.build_environment_url }}
        user-name: ${{ secrets.user_name }}
        password-secret: ${{ secrets.password }}
        solution-file: out/TeamsCreationAutomationWithPowerAutomate/TeamsCreation.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ secrets.build_environment_url }}
        user-name: ${{ secrets.user_name }}
        password-secret: ${{ secrets.password }}
        solution-name: TeamsCreation
        managed: true
        solution-output-file: out/ship/TeamsCreation.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: out/TeamsCreationAutomationWithPowerAutomate/TeamsCreation.zip

  release-to-qa:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release/

    - run: get-childitem .\out\release\

    - name: Import solution to qa env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ secrets.qa_environment_url }}
        user-name: ${{ secrets.user_name }}
        password-secret: ${{ secrets.password }}
        solution-file: out/release/TeamsCreation.zip
        force-overwrite: true
        publish-changes: true
